# Generated by Django 2.2 on 2020-06-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image',
        ),
        migrations.AddField(
            model_name='images',
            name='modified_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
