# Generated by Django 2.2 on 2020-06-23 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_images_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='modified_image',
        ),
    ]
