# Generated by Django 2.2 on 2020-06-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_images_modified_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='modified_image',
            field=models.ImageField(blank=True, null=True, upload_to='modified_images/'),
        ),
    ]
