# Generated by Django 2.2 on 2020-06-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_images_modified_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='modified_image',
            field=models.ImageField(blank=True, default=1, upload_to='modified_image/'),
            preserve_default=False,
        ),
    ]
