# Generated by Django 2.2 on 2020-06-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=40)),
                ('modified_image', models.ImageField(blank=True, null=True, upload_to='modified_images/')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
