# Generated by Django 2.2 on 2020-06-25 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_imageo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageO',
            new_name='Image',
        ),
    ]
